api_server:
  url: "localhost:8089"

experiment:
  cycle_length: 30
  init_process:
    - heater_on
  loop_process:
    - illumination_on 0 0 0.5 0.5
    - wait 10
    - mix
    - wait 10
    - air
    - wait 10
    - pump
    - wait 10
    - illumination_on 0 1.0 0 0
    - wait 10

mixer:
  rpm: 1000
  length: 10

aerator:
  volume: 50

heater:
  temperature: 28

pump:
  volume: 3
  flowrate: 30

illumination:
  channel_0: 0.5
  channel_1: 0.5
  channel_2: 0.0
  channel_3: 0.0
