api_server:
  url: "192.168.1.241:8089"

experiment:
  cycle_length: 10
  init_process:
    - heater_on
    - illumination_on
  loop_process:
    - mix
    - air
    - pump
    - wait

mixer:
  rpm: 1000
  length: 10

aerator:
  volume: 50

heater:
  intensity: 0.5

pump:
  volume: 3

illumination:
  channel_0: 0.5
  channel_1: 0.5
  channel_2: 0.0
  channel_3: 0.0
